services:
    LSB\ProductBundle\Factory\ProductFactory: ~

    lsb_product_factory_product:
        alias: 'LSB\ProductBundle\Factory\ProductFactory'

    LSB\ProductBundle\Factory\ProductFactoryInterface: '@LSB\ProductBundle\Factory\ProductFactory'

    LSB\ProductBundle\Factory\ProductSetProductFactory: ~

    lsb_product_factory_product_set_product:
        alias: 'LSB\ProductBundle\Factory\ProductSetProductFactory'

    LSB\ProductBundle\Factory\ProductSetProductFactoryInterface: '@LSB\ProductBundle\Factory\ProductSetProductFactory'

    LSB\ProductBundle\Factory\AssortmentGroupFactory: ~

    lsb_product_factory_assortment_group:
        alias: LSB\ProductBundle\Factory\AssortmentGroupFactory

    LSB\ProductBundle\Factory\AssortmentGroupFactoryInterface: '@LSB\ProductBundle\Factory\AssortmentGroupFactory'

    LSB\ProductBundle\Factory\SupplierFactory: ~

    lsb_product_factory_supplier:
        alias: LSB\ProductBundle\Factory\SupplierFactory

    LSB\ProductBundle\Factory\SupplierFactoryInterface: '@LSB\ProductBundle\Factory\SupplierFactory'

    LSB\ProductBundle\Factory\CategoryFactory: ~

    lsb_product_factory_category:
        alias: LSB\ProductBundle\Factory\CategoryFactory
    LSB\ProductBundle\Factory\CategoryFactoryInterface: '@LSB\ProductBundle\Factory\CategoryFactory'

    LSB\ProductBundle\Factory\ProductCategoryFactory: ~

    lsb_product_factory_product_category:
        alias: LSB\ProductBundle\Factory\ProductCategoryFactory
    LSB\ProductBundle\Factory\ProductCategoryFactoryInterface: '@LSB\ProductBundle\Factory\ProductCategoryFactory'

    LSB\ProductBundle\Factory\CategoryTranslationFactory: ~

    lsb_product_factory_category_translation:
        alias: LSB\ProductBundle\Factory\CategoryTranslationFactory
    LSB\ProductBundle\Factory\CategoryTranslationFactoryInterface: '@LSB\ProductBundle\Factory\CategoryTranslationFactory'

    LSB\ProductBundle\Factory\StorageFactory: null
    lsb_product_factory_storage:
        alias: LSB\ProductBundle\Factory\StorageFactory
    LSB\ProductBundle\Factory\StorageFactoryInterface: '@LSB\ProductBundle\Factory\StorageFactory'

    LSB\ProductBundle\Factory\ProductQuantityFactory: null
    lsb_product_factory_product_quantity:
        alias: LSB\ProductBundle\Factory\ProductQuantityFactory
    LSB\ProductBundle\Factory\ProductQuantityFactoryInterface: '@LSB\ProductBundle\Factory\ProductQuantityFactory'