services:
    LSB\ProductBundle\Form\ProductType:
        tags:
            - { name: form.type }

    LSB\ProductBundle\Form\ProductTranslationType:
        tags:
            - { name: form.type }

    LSB\ProductBundle\Form\CategoryType:
        tags:
            - { name: form.type }

    LSB\ProductBundle\Form\CategoryTranslationType:
        tags:
            - { name: form.type }

    LSB\ProductBundle\Form\ProductCategoryType:
        tags:
            - { name: form.type }

    LSB\ProductBundle\Form\ProductSetProductType:
        tags:
            - { name: form.type }
        arguments:
            $productManager: '@LSB\ProductBundle\Manager\ProductManager'

    LSB\ProductBundle\Form\AssortmentGroupType:
        tags:
            - { name: form.type }

    LSB\ProductBundle\Form\AssortmentGroupTranslationType:
        tags:
            - { name: form.type }

    LSB\ProductBundle\Form\SupplierType:
        tags:
            - { name: form.type }

    LSB\ProductBundle\Form\SupplierTranslationType:
        tags:
            - { name: form.type }

    LSB\ProductBundle\Form\StorageType:
        tags:
            - { name: form.type }

    LSB\ProductBundle\Form\StorageTranslationType:
        tags:
            - { name: form.type }