services:
    LSB\ProductBundle\Manager\ProductManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\ProductBundle\Manager\AssortmentGroupManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\ProductBundle\Manager\ProductSetProductManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\ProductBundle\Manager\SupplierManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\ProductBundle\Manager\CategoryManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\ProductBundle\Manager\ProductCategoryManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\ProductBundle\Manager\StorageManager:
        arguments:
            - '@lsb_utility_object_manager'