services:
    LSB\ProductBundle\Service\StorageService:
        arguments:
            - '@parameter_bag'
            - '@LSB\ProductBundle\Manager\ProductQuantityManager'
            - '@LSB\ProductBundle\Manager\StorageManager'

    LSB\ProductBundle\Service\StorageBookingService:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@parameter_bag'
            - '@LSB\ProductBundle\Manager\StorageManager'
            - '@LSB\ProductBundle\Service\StorageService'
            - '@LSB\ProductBundle\Manager\ProductQuantityManager'