language: php

php:
  - 7.3

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  #- wget https://scrutinizer-ci.com/ocular.phar
  #- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
