<?php
declare(strict_types=1);

namespace LSB\ProductBundle\Form;

use LSB\UtilityBundle\Form\BaseEntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class ProductTranslationType
 * @package LSB\ProductBundle\Form
 */
class ProductTranslationType extends BaseEntityType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add(
                'name',
                TextType::class
            )
            ->add(
                'additionalName',
                TextType::class
            )
            ->add(
                'slug',
                TextType::class
            )
            ->add(
                'unit',
                TextType::class
            )
            ->add(
                'locale',
                TextType::class
            )
        ;
    }

}