<?php
declare(strict_types=1);

namespace LSB\ProductBundle\Form;

use LSB\UtilityBundle\Form\BaseEntityType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class ProductTranslationType
 * @package LSB\ProductBundle\Form
 */
class ProductTranslationType extends BaseEntityType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add(
                'name',
                TextType::class,
                [
                    'required' => false,
                    'documentation' => [
                        'maxLength' => 255
                    ]
                ]
            )
            ->add(
                'additionalName',
                TextType::class,
                [
                    'required' => false,
                    'documentation' => [
                        'maxLength' => 255
                    ]
                ]
            )
            ->add(
                'slug',
                TextType::class,
                [
                    'required' => false,
                    'documentation' => [
                        'maxLength' => 255
                    ]
                ]
            )
            ->add(
                'description',
                TextareaType::class,
                [
                    'required' => false
                ]
            )
            ->add(
                'unit',
                TextType::class,
                [
                    'required' => false,
                    'documentation' => [
                        'maxLength' => 15
                    ]
                ]
            )
            ->add(
                'locale',
                TextType::class,
                [
                    'required' => false,
                    'documentation' => [
                        'maxLength' => 5
                    ]
                ]
            );
    }

}